"use client";
import Head from "next/head";
import LocationSearchBar from "../components/LocationSearchBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        className="d-flex flex-column justify-content-center align-items-center vh-100"
        style={{}}
      >
        <h1 className="text-center m-3">Weather Forecast App</h1>
        <LocationSearchBar />
      </div>
    </>
  );
}
